---

##########################################################
- name: include ansible-setup.yml
  include: ansible-setup.yml
  tags: ['ansible-setup']

- name: include sudoers.yml
  include: sudoers.yml
  tags: ['sudoers']
  when: configure_sudoers

- name: include terminal.yml
  include: terminal.yml
  tags: ['terminal']
  when: configure_terminal

- name: include osx.yml
  include: osx.yml
  tags: ['osx']
  when: configure_osx

- name: include extra-packages.yml
  include: extra-packages.yml
  tags: ['extra-packages']

# NOTE: Put this in playbook
# - name: Run configured post-provision ansible task files.
#   include_tasks: "{{ outer_item }}"
#   loop_control:
#     loop_var: outer_item
#   with_fileglob: "{{ post_provision_tasks|default(omit) }}"
