---
# SOURCE: https://github.com/geerlingguy/mac-dev-playbook/blob/df25444b3f08e1c5a2c7b941d0a49850514f9d98/.travis.yml
sudo: required
language: objective-c
# 10.13 (see https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version)
osx_image: xcode9.3

before_install:
  # Uninstall existing Homebrew installation.
  - curl -sLO https://raw.githubusercontent.com/Homebrew/install/master/uninstall
  - chmod +x ./uninstall
  - ./uninstall --force
  - sudo rm -rf /usr/local/Homebrew
  - sudo rm -rf /usr/local/Caskroom
  - sudo rm -rf /usr/local/bin/brew

install:
  # Install pip.
  - sudo easy_install pip

  # Install Ansible.
  - sudo pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Add a hosts file.
  - sudo mkdir -p /etc/ansible
  - sudo touch /etc/ansible/hosts
  - "echo -e '[local]\nlocalhost ansible_connection=local' | sudo tee -a /etc/ansible/hosts > /dev/null"

script:
  - _USER=travis
  - _GROUP=staff
  - _TRAVIS_CI=1
  - echo $_USER
  - echo $_GROUP
  # Test the playbook.
  # - "travis_wait 30 source install.sh"
  - cp -a $(pwd) ~/.dotfiles
  - ls -lta ~/.dotfiles
  - make sed-travis
  - make cp-config-travis
  - cat ~/.dotfiles/ansible/provision.sh
  - source ~/.dotfiles/install.sh
  - "travis_wait 1 /bin/bash -l -c 'pyenv versions'"
