# ~/.tmuxinator/local.yml

name: local
root: ~/

# Optional. tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# start scarlett
pre: who

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
pre_window: eval "$(rbenv init -)"; rbenv shell 2.6.6; . /usr/local/opt/dvm/dvm.sh; . $DVM_DIR/bash_completion

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

windows:
  - neofetch:
      layout: 9fa4,223x75,0,0{118x75,0,0[118x52,0,0{59x52,0,0,8,58x52,60,0,13},118x22,0,53,12],104x75,119,0[104x16,119,0,1,104x15,119,17,9,104x22,119,33,2,104x19,119,56,3]}
      panes:
        - neofetch:
          - neofetch
