---
downloads: ~/.ansible-downloads/

configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - rbenv
  - ruby-build
  - tree
  - ctags
  - ack
  - pkg-config
  - pyenv
  - pyenv-virtualenv
  - pyenv-virtualenvwrapper
  - jenv
  - ccache
  - pyenv-ccache

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - facebook/fb
  - homebrew/bundle
  - homebrew/completions
  - homebrew/dupes
  - homebrew/php
  - homebrew/science
  - homebrew/services
  - homebrew/versions
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - dropbox
  # - firefox
  - google-chrome
  - handbrake
  - iterm2
  - licecap
  - limechat
  - macvim
  - sequel-pro
  - skitch
  - slack
  - sublime-text
  - transmit
  - vagrant

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: pry
  #   state: present
  # - name: bundler
  #   state: present
  # - name: ruby-debug-ide
  #   version: "0.6.0"
  #   state: present
  # - name: debase
  #   version: "0.2.2.beta10"
  #   state: present
  # - name: rcodetools
  #   state: present
  # - name: rubocop
  #   state: present
  # - name: fastri
  #   state: present
  # - name: htmlbeautifier
  #   state: present
  # - name: hirb
  #   state: present
  # - name: pry-doc
  #   state: present
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
