---
- hosts: localhost
  tags:
    - rbenv
  become: yes
  become_method: sudo
  # SOURCE: https://docs.ansible.com/ansible/latest/playbooks_environment.html
  environment:
    SHELL: /bin/bash
  vars:
    bossjones__user: vagrant
    bossjones__group: vagrant
    ulimit_config:
      - domain: '*'
        type: soft
        item: nofile
        value: 64000
      - domain: '*'
        type: hard
        item: nofile
        value: 64000
  roles:
    - role: ulimit
    - role: zzet.rbenv
      default_gems_file: "/home/{{ bossjones__user }}/.dotfiles/ruby/default-gems"
      rbenv_extra_depends:
      - libjemalloc1
      - libjemalloc-dev
      - ctags
      rbenv:
        env: user
        version: v1.1.1
        default_ruby: 2.4.2
        rubies:
        - version: 2.4.2
      rbenv_users:
      - "{{ bossjones__user }}"
      rbenv_repo: "https://github.com/rbenv/rbenv.git"
      rbenv_plugins:
        - { name: "rbenv-vars",         repo: "https://github.com/rbenv/rbenv-vars.git",         version: "master" }
        - { name: "ruby-build",         repo: "https://github.com/rbenv/ruby-build.git",         version: "master" }
        - { name: "rbenv-default-gems", repo: "https://github.com/rbenv/rbenv-default-gems.git", version: "master" }
        - { name: "rbenv-installer",    repo: "https://github.com/rbenv/rbenv-installer.git",    version: "master" }
        - { name: "rbenv-update",       repo: "https://github.com/rkh/rbenv-update.git",         version: "master" }
        - { name: "rbenv-whatis",       repo: "https://github.com/rkh/rbenv-whatis.git",         version: "master" }
        - { name: "rbenv-use",          repo: "https://github.com/rkh/rbenv-use.git",            version: "master" }
        - { name: "rbenv-ctags",        repo: "https://github.com/tpope/rbenv-ctags.git",        version: "master" }
        - { name: "rbenv-each",         repo: "https://github.com/rbenv/rbenv-each.git",        version: "master" }
        - { name: "rbenv-aliases",      repo: "https://github.com/tpope/rbenv-aliases.git",        version: "master" }

      rbenv_root: "{% if rbenv.env == 'system' %}/usr/local/rbenv{% else %}~/.rbenv{% endif %}"


- hosts: localhost
  tags:
    - nvm
  become: yes
  become_method: sudo
  vars:
    bossjones__user: vagrant
    bossjones__group: vagrant
  # SOURCE: https://docs.ansible.com/ansible/latest/playbooks_environment.html
  environment:
    SHELL: /bin/bash
  roles:
    - role: pablocrivella.nvm
      nvm_repo: "git://github.com/creationix/nvm.git"
      nvm_root: "/home/{{ bossjones__user }}/.nvm"
      nvm_env: user
      nvm_version: v0.33.1
      nvm_default_node_version: stable
      nvm_node_versions:
        - stable
      nvm_global_packages:
        - vtop
        - whereami
        - figlet-cli
        - get-port-cli
        - getmac
        - mediumcli
        - speed-test
        - spoof
        - tldr
        - wireless-tools
        - yaml-lint
        - pathogen-pm
        - manga-scraper
        - gtop
        - historie
        - nodemon
        - npm
        - release-it
        - spot
        - superstatic
        - svgo
        - underscore-cli
      nvm_users:
        - "{{ bossjones__user }}"


- hosts: localhost
  tags:
    - pyenv
  vars:
    bossjones__user: vagrant
    bossjones__group: vagrant
  # become: yes
  # become_method: sudo
  # SOURCE: https://docs.ansible.com/ansible/latest/playbooks_environment.html
  environment:
    SHELL: /bin/bash
  roles:
    - role: avanov.pyenv
      pyenv_path: "/home/{{ bossjones__user }}/.pyenv"
      pyenv_owner: "{{ bossjones__user }}"
      pyenv_update_git_install: no
      pyenv_enable_autocompletion: yes
      pyenv_python_versions:
        - "3.6.4"
        - "2.7.14"
      pyenv_virtualenvs:
        - venv_name: "env364"
          py_version: "3.6.4"

        - venv_name: "env2714"
          py_version: "2.7.14"
  post_tasks:

    # Install plugins for pyenv
    - name: Clone pyenv-virtualenvwrapper
      git:
        repo: https://github.com/pyenv/pyenv-virtualenvwrapper
        dest: "/home/{{ bossjones__user }}/.pyenv/plugins/pyenv-virtualenvwrapper"
        version: "master"
        update: "{{ pyenv_update_git_install }}"

    - name: Clone pyenv-pip-rehash
      git:
        repo: https://github.com/pyenv/pyenv-pip-rehash
        dest: "/home/{{ bossjones__user }}/.pyenv/plugins/pyenv-pip-rehash"
        version: "master"
        update: "{{ pyenv_update_git_install }}"

    - name: Clone pyenv-pip-migrate
      git:
        repo: https://github.com/pyenv/pyenv-pip-migrate
        dest: "/home/{{ bossjones__user }}/.pyenv/plugins/pyenv-pip-migrate"
        version: "master"
        update: "{{ pyenv_update_git_install }}"

    - name: Clone pyenv-update
      git:
        repo: https://github.com/pyenv/pyenv-update
        dest: "/home/{{ bossjones__user }}/.pyenv/plugins/pyenv-update"
        version: "master"
        update: "{{ pyenv_update_git_install }}"

    - name: Clone pyenv-doctor
      git:
        repo: https://github.com/pyenv/pyenv-doctor
        dest: "/home/{{ bossjones__user }}/.pyenv/plugins/pyenv-doctor"
        version: "master"
        update: "{{ pyenv_update_git_install }}"

    # - name: Clone pyenv-ccache
    #   git:
    #     repo: https://github.com/pyenv/pyenv-ccache
    #     dest: "/home/{{ bossjones__user }}/.pyenv/plugins/pyenv-ccache"
    #     version: "master"

    - name: Clone pyenv-default-packages
      git:
        repo: https://github.com/jawshooah/pyenv-default-packages
        dest: "/home/{{ bossjones__user }}/.pyenv/plugins/pyenv-default-packages"
        version: "master"
        update: "{{ pyenv_update_git_install }}"
