---
- hosts: localhost
  tags:
    - rbenv
  become: yes
  become_method: sudo
  # SOURCE: https://docs.ansible.com/ansible/latest/playbooks_environment.html
  environment:
    SHELL: /bin/bash
  vars:
    ulimit_config:
      - domain: '*'
        type: soft
        item: nofile
        value: 64000
      - domain: '*'
        type: hard
        item: nofile
        value: 64000
  roles:
    - role: ulimit
    - role: zzet.rbenv
      default_gems_file: /home/test/.dotfiles/ruby/default-gems
      rbenv_extra_depends:
      - libjemalloc1
      - libjemalloc-dev
      - ctags
      rbenv:
        env: user
        version: v1.1.1
        default_ruby: 2.4.2
        rubies:
        - version: 2.4.2
      rbenv_users:
      - "test"
      rbenv_repo: "https://github.com/rbenv/rbenv.git"
      rbenv_plugins:
        - { name: "rbenv-vars",         repo: "https://github.com/rbenv/rbenv-vars.git",         version: "master" }
        - { name: "ruby-build",         repo: "https://github.com/rbenv/ruby-build.git",         version: "master" }
        - { name: "rbenv-default-gems", repo: "https://github.com/rbenv/rbenv-default-gems.git", version: "master" }
        - { name: "rbenv-installer",    repo: "https://github.com/rbenv/rbenv-installer.git",    version: "master" }
        - { name: "rbenv-update",       repo: "https://github.com/rkh/rbenv-update.git",         version: "master" }
        - { name: "rbenv-whatis",       repo: "https://github.com/rkh/rbenv-whatis.git",         version: "master" }
        - { name: "rbenv-use",          repo: "https://github.com/rkh/rbenv-use.git",            version: "master" }
        - { name: "rbenv-ctags",        repo: "https://github.com/tpope/rbenv-ctags.git",        version: "master" }
        - { name: "rbenv-each",         repo: "https://github.com/rbenv/rbenv-each.git",        version: "master" }
        - { name: "rbenv-aliases",      repo: "https://github.com/tpope/rbenv-aliases.git",        version: "master" }

      rbenv_root: "{% if rbenv.env == 'system' %}/usr/local/rbenv{% else %}~/.rbenv{% endif %}"


- hosts: localhost
  tags:
    - nvm
  become: yes
  become_method: sudo
  # SOURCE: https://docs.ansible.com/ansible/latest/playbooks_environment.html
  environment:
    SHELL: /bin/bash
  # vars:
  #   ulimit_config:
  #     - domain: '*'
  #       type: soft
  #       item: nofile
  #       value: 64000
  #     - domain: '*'
  #       type: hard
  #       item: nofile
  #       value: 64000
  roles:
    - role: pablocrivella.nvm
      nvm_repo: "git://github.com/creationix/nvm.git"
      nvm_root: "/home/test/.nvm"
      nvm_env: user
      nvm_version: v0.33.1
      nvm_default_node_version: stable
      nvm_node_versions:
        - stable
      nvm_global_packages:
        - vtop
        - whereami
        - figlet-cli
        - get-port-cli
        - getmac
        - mediumcli
        - speed-test
        - spoof
        - tldr
        - wireless-tools
        - yaml-lint
        - pathogen-pm
        - manga-scraper
      nvm_users:
        - "test"


- hosts: localhost
  tags:
    - pyenv
  become: yes
  become_method: sudo
  # SOURCE: https://docs.ansible.com/ansible/latest/playbooks_environment.html
  environment:
    SHELL: /bin/bash
  roles:
    - role: avanov.pyenv
      pyenv_path: "/home/test/.pyenv"
      pyenv_owner: "test"
      pyenv_update_git_install: no
      pyenv_enable_autocompletion: yes
      pyenv_python_versions:
        - "3.6.4"
        - "2.7.14"
      pyenv_virtualenvs:
        - venv_name: "env352"
          py_version: "3.5.2"

        - venv_name: "env2711"
          py_version: "2.7.11"
  post_tasks:

    # Install plugins for pyenv
    - name: Clone pyenv-virtualenvwrapper
      git:
        repo: https://github.com/pyenv/pyenv-virtualenvwrapper
        dest: "/home/test/.pyenv/plugins/pyenv-virtualenvwrapper"
        version: "master"

    - name: Clone pyenv-pip-rehash
      git:
        repo: https://github.com/pyenv/pyenv-pip-rehash
        dest: "/home/test/.pyenv/plugins/pyenv-pip-rehash"
        version: "master"

    - name: Clone pyenv-pip-migrate
      git:
        repo: https://github.com/pyenv/pyenv-pip-migrate
        dest: "/home/test/.pyenv/plugins/pyenv-pip-migrate"
        version: "master"

    - name: Clone pyenv-update
      git:
        repo: https://github.com/pyenv/pyenv-update
        dest: "/home/test/.pyenv/plugins/pyenv-update"
        version: "master"

    - name: Clone pyenv-doctor
      git:
        repo: https://github.com/pyenv/pyenv-doctor
        dest: "/home/test/.pyenv/plugins/pyenv-doctor"
        version: "master"

    # - name: Clone pyenv-ccache
    #   git:
    #     repo: https://github.com/pyenv/pyenv-ccache
    #     dest: "/home/test/.pyenv/plugins/pyenv-ccache"
    #     version: "master"

    - name: Clone pyenv-default-packages
      git:
        repo: https://github.com/jawshooah/pyenv-default-packages
        dest: "/home/test/.pyenv/plugins/pyenv-default-packages"
        version: "master"
